# Application name
spring.application.name=DemoFileManager

# Multipart file upload limits
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# --- Database Configuration (MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/file_manager1
spring.datasource.username=root
spring.datasource.password=Kalyan@28

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Logging ---
logging.level.root=INFO
logging.level.com.filemanager.fm=DEBUG

# --- Server port ---
server.port=9090
